// <auto-generated />
using System;
using IAPT.EK.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IAPT.EK.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191230231052_AddCCGCodeTable")]
    partial class AddCCGCodeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IAPT.EK.Business.Models.CCGCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Hub")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("cCGCodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f07cf020-ca14-46b6-ba49-35a11a53cc5e"),
                            Code = "01G",
                            Description = "NHS Salford CCG",
                            Hub = "Q73"
                        },
                        new
                        {
                            Id = new Guid("8f06832d-413b-4b28-a7e6-fdf3117e32e3"),
                            Code = "01M",
                            Description = "NHS North Manchester CCG"
                        },
                        new
                        {
                            Id = new Guid("8efddac3-61a5-4c0b-9159-45c792d18632"),
                            Code = "01N",
                            Description = "NHS North Manchester CCG",
                            Hub = "Q73"
                        },
                        new
                        {
                            Id = new Guid("185fc980-7013-4447-9573-b6e821218565"),
                            Code = "12F",
                            Description = "NHS Wirral CCG",
                            Hub = "Q75"
                        });
                });

            modelBuilder.Entity("IAPT.EK.Business.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49ea76ae-2749-4494-b360-dda9c7a6bea4"),
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = new Guid("c7848308-565a-438d-978e-d46a44617e95"),
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = new Guid("618b7307-038e-4921-ad02-2f3bb8a33ad5"),
                            Name = "Salfor"
                        },
                        new
                        {
                            Id = new Guid("11dbde9d-ae19-4835-9996-e2ea9be4c1b4"),
                            Name = "York"
                        },
                        new
                        {
                            Id = new Guid("b025b784-8c23-489a-9b04-ccc6e71998b3"),
                            Name = "Leeds"
                        },
                        new
                        {
                            Id = new Guid("77afa471-9031-449c-b118-df84efd86fbd"),
                            Name = "Chester"
                        },
                        new
                        {
                            Id = new Guid("f5c23c87-b9e2-4ea6-9087-cf789c9bdcc5"),
                            Name = "Oldhan"
                        });
                });

            modelBuilder.Entity("IAPT.EK.Business.Models.DisabilityCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DisabilityCode");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f5f310c-2020-451c-935b-985caead9951"),
                            Code = "01",
                            Description = "Behaviour and Emotional"
                        },
                        new
                        {
                            Id = new Guid("1237fd0c-4f2d-401d-b71b-ffd5a57f8602"),
                            Code = "02",
                            Description = "Hearing"
                        },
                        new
                        {
                            Id = new Guid("3ff48331-d5db-409e-9b5d-a258375880f3"),
                            Code = "03",
                            Description = "Manual Dexterity"
                        },
                        new
                        {
                            Id = new Guid("76f67c82-1b8d-4879-88fa-2f440c5770da"),
                            Code = "04",
                            Description = "Memory or ability to concentrate, learn or understand (Learning Disability)"
                        },
                        new
                        {
                            Id = new Guid("7c962c3f-808e-432b-bed3-c562379b4940"),
                            Code = "XX",
                            Description = "Other"
                        },
                        new
                        {
                            Id = new Guid("11108e16-58a6-4ec7-888c-75d163b13187"),
                            Code = "NN",
                            Description = "No Disability"
                        });
                });

            modelBuilder.Entity("IAPT.EK.Business.Models.EthnicCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int(5)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("EthnicCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf80022c-c615-4dc9-97e4-3a1e1ffb94f5"),
                            Code = "A",
                            Description = "White -British",
                            Sequence = 15
                        },
                        new
                        {
                            Id = new Guid("b49bce45-8392-49ef-b45d-3fc42e329ed0"),
                            Code = "B",
                            Description = "White - Irish",
                            Sequence = 20
                        },
                        new
                        {
                            Id = new Guid("1cecd654-55ea-46fc-bd33-4321687a9dbb"),
                            Code = "C",
                            Description = "White - Any other White background",
                            Sequence = 23
                        },
                        new
                        {
                            Id = new Guid("7e894fc5-6efe-4ff1-8621-8474555d06db"),
                            Code = "D",
                            Description = "Mixed - White and Black Caribbean",
                            Sequence = 25
                        },
                        new
                        {
                            Id = new Guid("d9ed2048-d3a5-4684-83fb-5556008d0d10"),
                            Code = "E",
                            Description = "Mixed - White and Black African",
                            Sequence = 30
                        },
                        new
                        {
                            Id = new Guid("9c355351-9e96-409b-a557-4f6096014fce"),
                            Code = "F",
                            Description = "Mixed - White and Asian",
                            Sequence = 35
                        },
                        new
                        {
                            Id = new Guid("45c17927-b80d-4684-9457-aaa07626ebb9"),
                            Code = "G",
                            Description = "Mixed - Any mixed backgroundn",
                            Sequence = 40
                        });
                });

            modelBuilder.Entity("IAPT.EK.Business.Models.ReligiousGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ReligiousGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2d355cf-263d-4004-bdba-437d63faaa6a"),
                            Code = "A",
                            Description = "Baha'i"
                        },
                        new
                        {
                            Id = new Guid("eb2fbe4f-16af-4eca-ac71-f0afde64e8bb"),
                            Code = "B",
                            Description = "Buddhist"
                        },
                        new
                        {
                            Id = new Guid("848d4cb1-085d-4e9d-b65d-cf01c20a083b"),
                            Code = "C",
                            Description = "Christian"
                        },
                        new
                        {
                            Id = new Guid("0ed436e1-86c7-4488-8373-1e0a4feb38de"),
                            Code = "D",
                            Description = "Hindu"
                        },
                        new
                        {
                            Id = new Guid("d3d8539e-3ecb-48b5-92ad-2e8163408083"),
                            Code = "E",
                            Description = "Jain"
                        },
                        new
                        {
                            Id = new Guid("1518b6d2-9471-47b7-bc9a-2b5bb34f2f99"),
                            Code = "F",
                            Description = "Jewish"
                        },
                        new
                        {
                            Id = new Guid("f0e5cc84-49ef-4178-a20f-aafd01b257da"),
                            Code = "G",
                            Description = "Muslim"
                        },
                        new
                        {
                            Id = new Guid("9be8b04e-fe30-49ff-8b4c-49c3c60285da"),
                            Code = "H",
                            Description = "Pagan"
                        },
                        new
                        {
                            Id = new Guid("567f1cae-a14c-4812-a919-615539473b10"),
                            Code = "I",
                            Description = "Sikh"
                        },
                        new
                        {
                            Id = new Guid("598e766c-9f01-4255-8988-1ef8d98607c6"),
                            Code = "J",
                            Description = "Zoroastrian"
                        },
                        new
                        {
                            Id = new Guid("94f08c31-f5de-4d32-8178-916e5a7b206c"),
                            Code = "K",
                            Description = "Other"
                        },
                        new
                        {
                            Id = new Guid("0efc089c-09e5-4c84-9049-31c31be6760e"),
                            Code = "L",
                            Description = "None"
                        },
                        new
                        {
                            Id = new Guid("5ecc0588-8f6f-4fc1-9f93-beabefcbd60b"),
                            Code = "M",
                            Description = "Declines to Disclose"
                        },
                        new
                        {
                            Id = new Guid("a0948204-2b15-4793-a1a6-18fef62e59f6"),
                            Code = "N",
                            Description = "Patient Religion Unknown"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
